Books/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
   url(r'^find/', views.findbookview, name = 'searchbooks'),
   url(r'^detail/(?P<slug>[-\w]+)/(?P<ISBN>[-\d]+)/', views.BookDetailView, name='detail'),
   url(r'^createchallenge/', views.ChallengeCreateView, name='createchallenge'),
   url(r'^like/', views.book_like, name='like'),
   url(r'^list', views.dummy, name='book_list',),
   url(r'^all/', views.BookListView, name='all'),
   ]

Booktracker/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from home import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.index),
    url(r'^account/', include('account.urls')),
    url(r'^books/', include('Books.urls', namespace='Books')),
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Books/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils.text import slugify
from django.core.urlresolvers import reverse
from sorl.thumbnail import ImageField
from django.contrib.auth.models import User



# Create your models here.
    
class Books(models.Model):
    title = models.CharField(max_length=200)
    author = models.CharField(max_length=200)
    ISBN = models.IntegerField(error_messages={})
    users_like=models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='books_liked', blank=True)
    slug = models.SlugField(max_length=200, blank=True)
 #  total_likes = models.PositiveIntegerField(db_index=True)
    coverpic = models.ImageField(upload_to='books/%Y/%m/%d', blank=True, null=True)


    def __str__(self):
        
        return '{} was written by {} and has ISBN number {} with {} likes'.format(self.title, self.author, self.ISBN, self.users_like.count(),)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
            super(Books, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('Books:detail', args=[self.slug, self.ISBN])

class BookPicture(models.Model):
    book = models.OneToOneField(Books)
    originalcoverpic  = models.ImageField(upload_to='books/%Y/%m/%d', blank=True, null=True)


class Review(models.Model):
    book = models.ForeignKey(Books, related_name='reviews')
    body = models.TextField()
    commenter = models.ForeignKey(User, related_name='commenter')
    created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Comment by {} on {}'.format(self.commenter, self.created)

class Challenge(models.Model):
    chalname = models.CharField(max_length=200)
    bookinchallenge = models.ManyToManyField(Books)

Books/forms.py
from django import forms
from django.forms import ModelForm
from .models import Books, Challenge, Review

class BookSearchForm(forms.Form):   
    title = forms.CharField(max_length=200)
    author = forms.CharField(max_length=200)
    ISBN = forms.IntegerField()


class BookCreateForm(forms.ModelForm):   
    class Meta:
        model = Books
        fields = ('title', 'author', 'ISBN', 'coverpic')


class ChallengeForm(forms.ModelForm):
    chal_name = forms.CharField(max_length=200)

    class Meta:
        model = Challenge
        fields = ('chal_name',)
 
class ChallengeItemForm(forms.Form):
    book_in_challenge = forms.ModelChoiceField(queryset=Books.objects.all().values())

    class Meta:
        model = Challenge
        fields = ('bookinchallenge',)

class ReviewForm(forms.ModelForm):
    class Meta:
        model = Review
        fields = ('body', 'commenter')
    
 

Books/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.contrib.auth import authenticate, login #, logout, login_then_logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from Booktracker.common.decorators import ajax_required
from django.views.decorators.http import require_POST
from .forms import BookSearchForm, BookCreateForm, ChallengeForm, ChallengeItemForm
from django.db.models import Count, Q
from .models import Books, Challenge
from django.core.exceptions import ValidationError
from django.http import HttpResponse, JsonResponse
from Booktracker.common.decorators import ajax_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from actions.utils import create_action



# Create your views here.
def dummy(request):
    #oddly necessary for findbookview to work
    pass

def findbookview(request):
    if request.method == 'POST':
        searchform = BookSearchForm(request.POST)
        
        if searchform.is_valid():
            cd = searchform.cleaned_data
            findbooks = Books.objects.filter(Q(title=cd['title']) | Q(author=cd['author']) | Q(ISBN=cd['ISBN']))

            if findbooks.count() == 0:
                if '_add' in request.POST:
                    addbookconfirm = BookCreateForm(data=request.POST, files=request.FILES)
                    if addbookconfirm.is_valid():
                        c_d = addbookconfirm.cleaned_data
                        Books.objects.create(title=c_d['title'], author=c_d['author'], ISBN=c_d['ISBN'], total_likes=0)

                        return render(request, 'book/added.html', {'addbookconfirm': addbookconfirm})

                else:
                    addbook = BookCreateForm()
                    addbook.fields['title'].initial = cd['title']
                    addbook.fields['author'].initial = cd['author']
                    addbook.fields['ISBN'].initial = cd['ISBN']

                    return render(request, 'book/notfound.html', {'addbook': addbook})
                
            else:
                 return render(request, 'book/foundbook.html', {'findbooks': findbooks})           

    else:
        searchform = BookSearchForm()


    return render(request, 'book/book.html', {'searchform': searchform })


@login_required
def BookListView(request):
    books = Books.objects.all()
    paginator = Paginator(books, 8)
    page = request.GET.get('page')
    try:
        books = paginator.page(page)
    except PageNotAnInteger:
        books = paginator.page(1)
    except EmptyPage:
        if request.is_ajax():
            return HttpResponse('')
        books = paginator.page(pagniator.num_pages)
    if request.is_ajax():
        return render(request, 'book/books/list_ajax.html', {'onpage':'books', 'books':books})
    return render(request, 'book/books/list.html', {'onpage':'books', 'books': books})
    


@login_required
def BookDetailView(request, slug, ISBN):
    book = get_object_or_404(Books, slug=slug, ISBN=ISBN)
 #   total_views = r.incr('book:{}:views'.format(book.id))
    reviews = Books.reviews.filter(active=True)
    
    return render(request, 'book/books/detail.html', {'section': 'challenges', 'book': book, })

@ajax_required
@login_required
@require_POST
def book_like(request):
    book_id = request.POST.get('id')
    action = request.POST.get('action')
    
    if book_id and action:
        try:
            book = Books.objects.get(id=book_id)
            if action == 'like':
                book.users_like.add(request.user)
            else:
                book.users_like.remove(request.user)
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status':'ko'})



@login_required
def ChallengeCreateView(request):
    if request.method == 'POST':
        new_chal = ChallengeForm(request.POST)
        if new_chal.is_valid():
            cd = new_chal.cleaned_data
            
            challenge = new_chal.save(commit=False)
            challenge.chalname=cd['chal_name']
            challenge.save()

            books = Books.objects.all()

            return render(request, 'book/books/additems.html', {'challenge': challenge, 'new_chal': new_chal, 'books': books})
    else:
        new_chal = ChallengeForm()
    return render(request, 'book/books/challengecreate.html', {'new_chal': new_chal, 'new_chal': new_chal})
        
@ajax_required
@login_required
@require_POST
def add_book(request):
    challenge_id = request.POST.get('id')
    book_id = request.POST.get('bookid')
    action = request.POST.get('action')
    
    if challenge_id and book_id and action:
        try:
            challenge = Challenge.objects.get(id=challenge_id)
            book = Books.objects.get(id=book_id)
            if action == 'add':
                challenge.bookinchallenge.add(book)
            else:
                challenge.bookinchallenge.remove(book)
            return JsonResponse({'status': 'ok'})
        except:
            pass
    return JsonResponse({'status':'ko'})
       
     

Books/templates/book/books/addbook.html
{% extends "base.html" %}
{% block title %}Create an account{% endblock %}
{% block content %}
<h1>Create an account</h1>
<p>Please, sign up using the following form:</p>
<form action="." method="POST">
{{ create.as_p }}
{% csrf_token %}
<input type="submit" value="register">
</form>

{% endblock %}

Books/templates/book/books/additems.html
{% extends 'base.html' %}
{% block content %}
<h1>{{ challenge.chalname }}</h1> {{ challenge.id }}

{{ challenge.bookinchallenge.all }} 
{% for book in books %} 
<h2> {{ book.title }} </h2> by {{ book.author }} with ISBN number {{ book.ISBN }}  {{book.id}}

<a href='#' data-id='{{challenge.id}}' data-bookid='{{ book.id }}' data-action='{% if book in challenge.bookinchallenge.all %}un{% else %}{% endif %}add' class='add button'>
{% if book in challenge.bookinchallenge %}Delete{%else%}Add{% endif %}
</a>
{% endfor %}

<span class='count'>
    <span class ='total'>
        <h4>Books in challenge:  {{ challenge.bookinchallenge.count }} </h4>
    </span>
</span> 
{% endblock %}
{% block domready %}
$('a.add').click(function(e){
    e.preventDefault();
    $.post('{% url 'Books:add_book' %}', { id:$(this).data('id'), bookid:$(this).data('bookid'), action:$(this).data('action') },
    function(data){
        if(data['status'] == 'ok'){
            var prev_act = $('a.add').data('action');
            $('a.add').data('action', prev_act == 'add' ? 'remove' : 'add');
            $('a.add').text('action', prev_act == 'add' ? 'Remove': 'Add');
            var prev_items = parseInt($('span.count .total').text());
            $('span.count .total').text(previous_act == 'add' ? prev_items+1 : prev_items-1);
          
}});

});


{% endblock %}

Books/templates/book/books/challengecreate.html
{% extends 'base.html' %}
{% block content %}
<form action="." method="POST"> 
    {{new_chal.as_p}}  {% csrf_token %}
<input type='submit' value='Save'>
</form>
{% endblock %}

Books/templates/book/books/detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}
<h1>{{ book.title }}</h1> 
<h3>PAGE: "Dating" Profile <br> </h3>
<h5>DEF: So-called as this is a page showing {{ book.title }}'s many details. If this book were a person, this page would be used to creepily stalk and gather information. Thank god it isn't, so you can't accidentally 'like' something either.</h5>
<div class='col-md-7'>

<h3>By: {{ book.author }}</h3>
<h4>ISBN: {{ book.ISBN }}</h4>
{% with total_likes=book.users_like.count %}
<span class='count'>
    <span class ='total'>
        <h4>Likes: {{ total_likes }} </h4>
    </span>
</span> 
    
</div>
<div class='col-md-4'>yess
     {% thumbnail books.coverpic '180x180' crop='100%' as im %} <img src='{{ im.url }}'> {% endthumbnail %} no
</div>


<a href='#' data-id='{{ book.id }}' data-action='{% if request.user in book.users_like.all %}un{% endif %}like' class='like button'> 
    {% if request.user not in book.users_like.all %} Like {% else %} Unlike {% endif %}
</a>

Coverpic:{{ book.coverpic }}
{% endwith %}

{% endblock %}

{% block domready %}
$('a.like').click(function(e){
    e.preventDefault();
    $.post('{% url 'Books:like' %}', { id: $(this).data('id'), action: $(this).data('action') },
    function(data){
        if(data['status'] == 'ok'){
            var previous_act = $('a.like').data('action');
            $('a.follow').data('action', previous_act == 'like' ? 'unlike' : 'like');
            $('a.follow').text('action', previous_act == 'like' ? 'Unlike': 'Like');
            var prev_likes = parseInt($('span.count .total').text());
            $('span.count .total').text(previous_act == 'like' ? prev_likes+1 : prev_likes-1);
          
}});

});


{% endblock %}

Books/templates/book/books/list.html
{% extends 'base.html' %}
{% block content %}
<div class='container'>

<div class='col-sm-12'>
<h4><a href='{% url 'Books:createchallenge' %}'>Create a challenge </a></h4>
<h4><a href='{% url 'Books:searchbooks' %}'>Search </a></h4>
</div>

<div class='col-md=9' id='booklist'>
{% include 'book/books/list_ajax.html' %}
</div>
</div>
{% endblock %}

{% block domready %}
    var page = 1;
    var empty_page = false;
    var block_request = false;
    
    $(window).scroll(function(){
        var margin = $(document).height() - $(window).height - 200;
        if ($(window).scrollTop() > margin && empty_page == false && block_request == false){
        block_request = true;
        page += 1'
$.get('?page=' + page, function(data){}
    if(data == ''){
empty_page = true;
}else{
    block_request = false;
    $('#booklist').append(data);
}
)
}

})

{% endblock %}

Books/templates/book/books/list_ajax.html
{% for book in books %}
<a href='{{ book.get_absolute_url }}'>{{ book.title }}</a>
{{ book.author }}
{% endfor %}